export const project = [
  {
    name: 'Movie App',
    info: 'Enables users to discover new releases and browse movies by genre with a clean, fast UI',
    tools: ['React', 'Tailwind', 'HTML', 'CSS'],
    img: '/cloud.png',
    link: 'https://ibrahim-movie-app.netlify.app/',
    tag: 'Frontend',
  },
  {
    name: 'Real Estate App',
    info: 'Discover and explore apartments to own or rent in Ibadan, Oyo State, Nigeria.',
    tools: ['React', 'Node.js', 'Tailwind'],
    img: '/ibad.jpeg',
    link: 'https://yemreality.netlify.app/',
    tag: 'Fullstack',
  },
  {
    name: 'E-commerce App',
    info:' Your trusted destination for affordable shopping and premium everyday essentials.',
    tools: ['React', 'Node.js', 'Tailwind'],
    img: './gemini.png',
    link: 'https://enaijaacommerce.onrender.com/',
    tag: 'Fullstack',
  },
  {
    name: 'Anonymous Message App.',
    info: 'Send anonymous message links so recipients can collect messages without knowing the sender.',
    tools: ['JavaScript', 'Bootstrap', 'HTML'],
    img: '/new.png',
    link: 'https://anonymous-app1.netlify.app/',
    tag: 'Frontend',
  },
  {
    name: 'Dictionary',
    info: 'Look up definitions of English words with a clean search interface.',
    tools: ['React', 'Tailwind'],
    img: '/dico.png',
    link: 'https://check-dictionary.netlify.app/',
    tag: 'Frontend',
  },
]