export const project = [
  {
    name: 'Movie App',
    info: 'Enables users to discover new releases and browse movies by genre with a clean, fast UI..',
    tools: ['React', 'Tailwind', 'HTML', 'CSS'],
    img: '/cloud.png',
    link: 'https://ibrahim-movie-app.netlify.app/',
    tag: 'Frontend',
  },
  {
    name: 'Real Estate App',
    info: 'Discover and explore apartments to own or rent in Ibadan, Oyo State, Nigeria.',
    tools: ['React', 'Node.js', 'Tailwind'],
    img: '/ibad.jpeg',
    link: 'https://yemreality.netlify.app/',
    tag: 'Fullstack',
  },
  {
    name: 'Anonymous Message App',
    info: 'Send anonymous message links so recipients can collect messages without knowing the sender.',
    tools: ['JavaScript', 'Bootstrap', 'HTML'],
    img: '/new.png',
    link: 'https://regal-dasik-41ecda.netlify.app/',
    tag: 'Frontend',
  },
  {
    name: 'School Portal',
    info: 'Students can sign up, receive a unique matric number, and access personalised dashboards.',
    tools: ['React', 'Tailwind', 'Node.js', 'MongoDB'],
    img: '/fully.png',
    link: 'https://timely-conkies-c49131.netlify.app/',
    tag: 'Fullstack',
  },
  {
    name: 'Game Plan',
    info: 'Users select game plans and subscribe to their preferred tier in a polished UI.',
    tools: ['React', 'Tailwind'],
    img: '/game.jpeg',
    link: 'https://game-plan.netlify.app/',
    tag: 'Frontend',
  },
  {
    name: 'Dictionary',
    info: 'Look up definitions of English words with a clean search interface.',
    tools: ['React', 'Tailwind'],
    img: '/logo.png',
    link: 'https://aesthetic-starship-78fcc7.netlify.app/',
    tag: 'Frontend',
  },
]